import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { FirstForm, SecondForm } from "../features/home";
import styles from "../features/home/Home.module.css";
const Home: NextPage = () => {
  const [stage, setStage] = useState(1);
  const [identification, setIdentification] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>MiContrato | Domina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {stage == 1 && <FirstForm setStage={setStage} setIdentification={setIdentification} />}
        {stage == 2 && <SecondForm identification={identification} />}
      </main>
    </div>
  );
};

export default Home;
